version: "3.9"
services:
  telegraf:
    container_name: "telegraf"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./docker/config.conf:/etc/telegraf/389ds-db-input.conf
  ds:
    container_name: "ds"
    image: "389ds/dirsrv:latest"
    volumes:
      - ./docker/bootstrap-389ds.sh:/usr/sbin/bootstrap-389ds.sh
      - ./docker/data:/data
    environment:
      - DS_DM_PASSWORD=password
    ports:
      - "389:3389"
      - "636:6636"